package org.ragunit.core.assertion;

import org.ragunit.core.domain.Answer;
import org.ragunit.core.domain.Document;
import org.ragunit.core.report.JsonFileReporter;
import org.ragunit.core.report.RagReporter;

import java.util.List;

/**
 * Entry point for RAGUnit's fluent assertion API.
 *
 * <p>Two evaluation flows are available:
 * <pre>{@code
 * // Retrieval: are the retrieved documents relevant to the question?
 * RagAssert.assertThatContext(retrievedDocs)
 *          .forQuestion(question)
 *          .evaluatedBy(judge)
 *          .hasRelevanceScore(0.85);
 *
 * // Generation: is the answer faithful and relevant?
 * RagAssert.assertThatAnswer(answer)
 *          .givenContext(retrievedDocs)
 *          .forQuestion(question)
 *          .evaluatedBy(judge)
 *          .isFaithfulToContext(0.90)
 *          .isRelevantToQuestion(0.85);
 * }</pre>
 *
 * <p>This class is not instantiable. Builders ({@code ContextAssert}, {@code AnswerAssert})
 * are package-private; reporters can be injected via the builders for testing.
 */
public final class RagAssert {

    private RagAssert() {
    }

    /**
     * Starts a Retrieval evaluation assertion for the given context documents.
     *
     * @param context the list of documents retrieved by the Retriever
     * @return a {@code ContextAssert} builder ready for chaining
     */
    public static ContextAssert assertThatContext(List<Document> context) {
        return new ContextAssert(context, defaultReporters());
    }

    /**
     * Starts a Generation evaluation assertion for the given answer.
     *
     * @param answer the text generated by the LLM
     * @return an {@code AnswerAssert} builder ready for chaining
     */
    public static AnswerAssert assertThatAnswer(Answer answer) {
        return new AnswerAssert(answer, defaultReporters());
    }

    private static List<RagReporter> defaultReporters() {
        return List.of(new JsonFileReporter());
    }
}
