package org.ragunit.core.domain;

import java.util.Objects;

/**
 * The text generated by the LLM based on the {@code Context}.
 *
 * @param text the generated answer text; must not be null
 */
public record Answer(String text) {

    /** Validates that the answer text is not null. */
    public Answer {
        Objects.requireNonNull(text, "text");
    }
}
